export default [
  {
    id: 1,
    postedOn: new Date(),
    title: "Frontend Developer",
    workType: "Full time",
    workStyle: "Remote",
    location: "Ha noi",
    companyName: "Google",
    salary: "10000000",
    degree: "12th pass",
    companyUrl: "Google.com",
    link: "https://google.com/careers",
  },
  {
    id: 2,
    postedOn: new Date(),
    title: "Backend Developer",
    workType: "Part time",
    workStyle: "in-Office",
    location: "Ha noi",
    companyName: "Yahoo",
    salary: "12000000",
    degree: "Diploma",
    companyUrl: "Yahoo.com",
    link: "https://yahoo.com/jobs",
  },
  {
    id: 3,
    postedOn: new Date(),
    title: "Mobile dev",
    workType: "Contract",
    workStyle: "Remote",
    location: "Ha noi",
    companyName: "Facebook",
    salary: "20000000",
    degree: "Bachelor's degree",
    companyUrl: "https://facebook.com",
    link: "https://facebook.com/careers",
  },
  {
    id: 4,
    postedOn: new Date(),
    title: "Cashier",
    workType: "Full time",
    workStyle: "in-Office",
    location: "Ha noi",
    companyName: "Iyuno-SDI Group",
    salary: "10000000",
    degree: "No degree",
    companyUrl: "Google.com",
    link: "https://google.com/careers",
  },
];
